[build]
  base = "dashboard"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://instagram-analyzer-api.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://instagram-analyzer-api.onrender.com/:splat"
  status = 200
  force = true