CREATE TABLE campaigns (
    campaign_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    budget DECIMAL(12,2) NOT NULL,
    start_date DATE,
    end_date DATE,
    application_deadline DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'RECRUITING' CHECK (status IN ('DRAFT',
    'RECRUITING',
    'ONGOING',
    'COMPLETED',
    'CANCELLED')),
    target_kpis JSONB,
    requirements JSONB,
    guidelines TEXT,
    campaign_type VARCHAR(50),
    target_categories JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);